# Generated by Django 4.2.5 on 2023-09-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 12, 0), verbose_name='Publish date')),
                ('content', models.TextField()),
                ('img_source', models.ImageField(upload_to='static/pharmacy/images/articles')),
            ],
        ),
    ]
