# Generated by Django 4.2.5 on 2023-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_source',
            field=models.ImageField(upload_to='media/images/news'),
        ),
    ]
