# Generated by Django 4.2.5 on 2023-09-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_img_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_source',
            field=models.ImageField(upload_to='static/images/news/'),
        ),
    ]
