# Generated by Django 4.2.5 on 2023-09-21 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 12, 0), verbose_name='Publish date')),
                ('text', models.TextField()),
                ('estimation', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Very Good')])),
            ],
        ),
    ]
