# Generated by Django 4.2.1 on 2023-06-04 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 3, 30, 14, 600548), verbose_name='Date sold'),
        ),
    ]
