# Generated by Django 4.2.1 on 2023-06-04 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 21, 29, 13, 83451), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 21, 29, 13, 82890), verbose_name='Date sold'),
        ),
    ]
