# Generated by Django 4.2.1 on 2023-06-04 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_employee_date_of_birth_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 21, 36, 40, 14102), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 21, 36, 40, 13560), verbose_name='Date sold'),
        ),
    ]
