# Generated by Django 4.2.1 on 2023-06-04 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_employee_date_of_birth_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2005, 6, 4, 22, 10, 45, 896317), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 22, 10, 45, 895789), verbose_name='Date sold'),
        ),
    ]
