# Generated by Django 4.2.1 on 2023-09-17 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_employee_date_of_birth_alter_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('img_source', models.ImageField(upload_to='images/articles')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2005, 9, 17, 15, 15, 44, 285019), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 15, 15, 44, 284454), verbose_name='Date sold'),
        ),
    ]
