# Generated by Django 4.2.1 on 2023-09-17 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_article_img_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 17, 26, 51, 828668), verbose_name='Date sold'),
        ),
    ]
