# Generated by Django 4.2.1 on 2023-09-17 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 12, 0), verbose_name='Publish date'),
        ),
    ]
