# Generated by Django 4.2.5 on 2023-09-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_article_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
